### ISSUE TITLE
Parsing sil.org threw an error

### ISSUE THREAD

**Issue by axtens** [flipbit/whois#8]
Tokens.Exceptions.TokenMatcherException
	  HResult=0x80131500
	  Message=Unable to assign: WhoisRedirect.ExpirationDate
	  Source=Tokenizer
	  StackTrace:
	   at Tokens.TokenMatcher.TryMatch[T](String input, TokenMatch`1& match)
	   at Whois.Visitors.RedirectVisitor.IsARedirectRecord(WhoisResponse response, WhoisRedirect& redirect)
	   at Whois.Visitors.RedirectVisitor.<Visit>d__1.MoveNext()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Whois.WhoisLookup.<LookupAsync>d__14.MoveNext()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Whois.WhoisLookup.<LookupAsync>d__13.MoveNext()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Whois.AsyncHelper.RunSync[TResult](Func`1 func)
	   at Whois.WhoisLookup.Lookup(String domain)
	   at Wrappers.Whois.Lookup(String domain_ip) in C:\Users\bugma\Source\Repos\BORR\Wrappers\Whois.cs:line 21

	Inner Exception 1:
	TokenAssignmentException: Unable to assign: WhoisRedirect.ExpirationDate

	Inner Exception 2:
	FormatException: String was not recognized as a valid DateTime.

Does this mean I need to write a parser for WhoisRedirect.ExpirationDate or that your WhoisRedirect.ExpirationDate couldn't handle what the whois of sil.org gave? Where to now?

**Comment by flipbit** [comment]
Looks like there was an issue parsing a date string that spilled over to the next line when extracting its value.  I've update the template to only extract data up until the newline now, so should be fixed if you pull the latest master branch now.

**Comment by flipbit** [comment]
This is fixed in version `2.0.2` of the library now.
