### ISSUE TITLE
System.TimeoutException on .net domains

### ISSUE THREAD

**Issue by Son1x90** [flipbit/whois#93]
System.TimeoutException: 'The operation has timed out.'

System.TimeoutException
  HResult=0x80131505
  Message=The operation has timed out.
  Source=Whois
  StackTrace:
   at Whois.Net.TcpReader.<Read>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Whois.WhoisLookup.<Download>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Whois.WhoisLookup.<LookupAsync>d__21.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Whois.AsyncHelper.RunSync[TResult](Func`1 func)
   at Whois.WhoisLookup.Lookup(String domain)
   at WhoisDomainNameChecker.Program.Main(String[] args) in E:\Dev\Projects\WhoisDomainNameChecker\WhoisDomainNameChecker\Program.cs:line 20

  This exception was originally thrown at this call stack:
    Whois.Net.TcpReader.Read(string, int, string, System.Text.Encoding, int)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    Whois.WhoisLookup.Download(string, Whois.WhoisRequest)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    Whois.WhoisLookup.LookupAsync(Whois.WhoisRequest)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]

**Comment by ckmcphee15** [comment]
Issue happens to me on Dev environment as well, basically with every TLD and ccTLD i use
